"""Initial migration

Revision ID: 180b39a402c5
Revises: 
Create Date: 2023-06-29 16:21:51.021909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180b39a402c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'user_id')
    # ### end Alembic commands ###
