"""Adding image link en movies

Revision ID: 88536f051ea5
Revises: a417a094a722
Create Date: 2023-07-13 14:25:02.240521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88536f051ea5'
down_revision = 'a417a094a722'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'image_link')
    # ### end Alembic commands ###
