"""Initial migration

Revision ID: a417a094a722
Revises: 830becff73ad
Create Date: 2023-07-12 19:36:47.137448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a417a094a722'
down_revision = '830becff73ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('imagen', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'imagen')
    # ### end Alembic commands ###
