"""Groups per user

Revision ID: d4c67f4ea131
Revises: 88536f051ea5
Create Date: 2023-07-31 15:15:51.664130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c67f4ea131'
down_revision = '88536f051ea5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
