"""Initial migration

Revision ID: fa5b054ab351
Revises: d01eec61b7ff
Create Date: 2023-07-12 19:32:45.769288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5b054ab351'
down_revision = 'd01eec61b7ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
